version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
      - DB_HOST=db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
